{
 "title": "Pure Storage FlashArray Volume detail",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(purefa_info, job)" } },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "label_values(purefa_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "filesystem",
    "label": "File System",
    "query": {
     "query": "label_values(purefa_volume_space_bytes{job=\"$job\",instance=\"$instance\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "purefa_volume_space_bytes{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",space=\"virtual\"}\n",
     "legendFormat": "{{ space }}"
    },
    {
     "expr": "purefb_file_systems_space_bytes{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",space=\"total_physical\"}",
     "legendFormat": "{{ space }}"
    },
    {
     "expr": "purefb_file_systems_space_bytes{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",space=\"unique\"}",
     "legendFormat": "{{ space }}"
    },
    {
     "expr": "purefb_file_systems_space_bytes{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",space=\"snapshots\"}",
     "legendFormat": "{{ space }}"
    },
    {
     "expr": "purefb_file_systems_space_bytes{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",space=\"provisioned\"}",
     "legendFormat": "{{ space }}"
    }
   ]
  },
  {
   "title": "average volume iops",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_volume_performance_throughput_iops{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "Volume data reduction ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_volume_space_data_reduction_ratio{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "average volume latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_latency_usec{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\"}) / 1000"
    }
   ]
  },
  {
   "title": "Volume capacity usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_volume_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"virtual\",name=\"$filesystem\"})\n/\nsum(purefa_volume_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_provisioned\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "iops read ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_volume_performance_throughput_iops{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",dimension=\"reads_per_sec\"})\n/\nsum(purefa_volume_performance_throughput_iops{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "iops write ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_volume_performance_throughput_iops{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",dimension=\"writes_per_sec\"})\n/\nsum(purefa_volume_performance_throughput_iops{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "average volume throughput",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_volume_performance_bandwidth_bytes{instance=\"$instance\",job=\"$job\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "volume capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_volume_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"virtual\",name=\"$filesystem\"}"
    }
   ]
  },
  {
   "title": "Volume iops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(purefa_volume_performance_throughput_iops{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\",dimension=\"reads_per_sec\"})",
     "legendFormat": "{{filesystem}} read "
    },
    {
     "expr": "sum(\n  purefa_volume_performance_throughput_iops{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\",dimension=\"writes_per_sec\"}\n)",
     "legendFormat": "{{filesystem}} write "
    }
   ]
  },
  {
   "title": "Volume latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_performance_latency_usec{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\", dimension=\"usec_per_read_op\"}\n) / 1000",
     "legendFormat": "{{ volume}} read "
    },
    {
     "expr": "sum(\n  purefb_file_systems_performance_latency_usec{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\",dimension=\"usec_per_write_op\"}\n) / 1000",
     "legendFormat": "{{ volume}} write "
    }
   ]
  },
  {
   "title": "Volume throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_performance_bandwidth_bytes{instance=\"$instance\",job=\"$job\",name=\"$filesystem\", dimension=\"read_bytes_per_sec\"}\n)",
     "legendFormat": "{{ volume}} read "
    },
    {
     "expr": "sum(\n  purefb_file_systems_performance_bandwidth_bytes{instance=\"$instance\",job=\"$job\",name=\"$filesystem\",dimension=\"write_bytes_per_sec\"}\n)",
     "legendFormat": "{{ volume}} write "
    }
   ]
  },
  {
   "title": "Volume avg bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_performance_average_bytes{instance=\"$instance\",job=\"$job\",name=\"$filesystem\", dimension=\"bytes_per_read\"}\n)",
     "legendFormat": "{{ volume}} read "
    },
    {
     "expr": "sum(\n  purefa_volume_performance_average_bytes{instance=\"$instance\",job=\"$job\",name=\"$filesystem\",dimension=\"bytes_per_write\"}\n)",
     "legendFormat": "{{ volume}} write "
    }
   ]
  }
 ]
}