{
 "title": "Pure Storage FlashArray landscape",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(purefa_info, job)" } },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "label_values(purefa_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <h1>Pure Storage FlashArray</h1>\n</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "info",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_alerts_open{job=~\"$job\", instance=~\"$instance\", severity=\"info\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "warnings",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_alerts_open{job=~\"$job\",instance=~\"$instance\",component_name=\"warning\"})"
    }
   ]
  },
  {
   "title": "critical",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_alerts_open{job=~\"$job\",instance=~\"$instance\",component_name=\"critical\"})"
    }
   ]
  },
  {
   "title": "hardware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(purefa_hw_component_status{job=~\"$job\",instance=~\"$instance\"})-sum(purefa_hw_component_status{job=~\"$job\",instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "capacity usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\"})\n/\nsum(purefa_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\"})"
    }
   ]
  },
  {
   "title": "data reduction",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_data_reduction_ratio{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "average iops",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_throughput_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "average throughput",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_bandwidth_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "average IO latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_latency_usec{job=~\"$job\",instance=~\"$instance\"}) / 1000"
    }
   ]
  }
 ]
}