{
 "title": "Pure Storage FlashArray system detail",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(purefa_info, job)" } },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "label_values(purefa_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{array_name}}"
    }
   ]
  },
  {
   "title": "firmware",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "system events",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefa_alerts_open{job=~\"$job\",instance=~\"$instance\"}) by(component_name)",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  {
   "title": "average iops",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_throughput_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "average latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_latency_usec{job=~\"$job\",instance=~\"$instance\"}) / 1000"
    }
   ]
  },
  {
   "title": "average throughput",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_bandwidth_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_data_reduction_ratio{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "hardware health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefa_hw_component_status{job=~\"$job\",instance=~\"$instance\"} == 0)"
    }
   ]
  },
  {
   "title": "array capacity usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\"})\n/\nsum(purefa_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\"})"
    }
   ]
  },
  {
   "title": "io ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_performance_throughput_iops{job=~\"$job\",instance=~\"$instance\",dimension=\"writes_per_sec\"})\n/\nsum(purefa_array_performance_throughput_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "write"
    },
    {
     "expr": "sum(purefa_array_performance_throughput_iops{job=~\"$job\",instance=~\"$instance\",dimension=\"reads_per_sec\"})\n/\nsum(purefa_array_performance_throughput_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(purefa_array_performance_iops{job=~\"$job\",instance=~\"$instance\",dimension=\"other\"})\n/\nsum(purefa_array_performance_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_bytes{job=~\"$job\",instance=\"$instance\"}) by (space)",
     "legendFormat": "{{ space }}"
    },
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=\"$instance\",space=\"capacity\",type=\"array\"})\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=\"$instance\",space=\"total_physical\",type=\"array\"})",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "4 week capacity delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  delta(\n    purefa_array_space_bytes{job=~\"$job\",instance=\"$instance\",space=\"total_physical\"}[4w]\n  )\n)"
    }
   ]
  },
  {
   "title": "array performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "array iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(purefa_array_performance_throughput_iops{job=~\"$job\",instance=\"$instance\",dimension=\"reads_per_sec\"})",
     "legendFormat": "read "
    },
    {
     "expr": "sum(purefa_array_performance_throughput_iops{job=~\"$job\",instance=\"$instance\",dimension=\"writes_per_sec\"})",
     "legendFormat": "write "
    },
    {
     "expr": "sum(purefa_array_performance_throughput_iops{job=~\"$job\",instance=\"$instance\",dimension=\"other\"})",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "array latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(purefa_array_performance_latency_usec{job=~\"$job\",instance=\"$instance\",dimension=\"usec_per_read_op\"})",
     "legendFormat": "read "
    },
    {
     "expr": "sum(purefa_array_performance_latency_usec{job=~\"$job\",instance=\"$instance\",dimension=\"usec_per_write_op\"})",
     "legendFormat": "write "
    },
    {
     "expr": "sum(purefa_array_performance_latency_usec{job=~\"$job\",instance=\"$instance\",dimension=\"usec_per_other_op\"})",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "array throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(purefa_array_performance_bandwidth_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"read_bytes_per_sec\"})",
     "legendFormat": "read "
    },
    {
     "expr": "sum(purefa_array_performance_bandwidth_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"write_bytes_per_sec\"})",
     "legendFormat": "write "
    }
   ]
  },
  {
   "title": "top talker volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  }
 ]
}