{
 "title": "Pure Storage FlashArray system hardware health",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(purefa_info, job)" } },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "label_values(purefa_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(purefa_hw_component_status{instance=~\"$instance\",component_type=\"controller\"}, component_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "system events",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefa_alerts_open{job=~\"$job\",instance=~\"$instance\"}) by(component_name)",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  {
   "title": "capacity usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_bytes{job=~\"$job\", instance=~\"$instance\", space=\"total_physical\"}) / sum(purefa_array_space_bytes{job=~\"$job\", instance=~\"$instance\", space=\"capacity\"})"
    }
   ]
  },
  {
   "title": "average iops",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_throughput_iops{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "chassis health",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hw_component_status{job=\"$job\", instance=\"$instance\", component_type=\"chassis\", component_status=\"ok\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "average IO latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_latency_usec{job=~\"$job\",instance=~\"$instance\"}) / 1000"
    }
   ]
  },
  {
   "title": "firmware version",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "data reduction",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_data_reduction_ratio{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "average throughput",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_bandwidth_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "failed controller ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hw_component_status{job=\"$job\", instance=\"$instance\", component_type=\"controller\", component_status=\"ok\"} != 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Failed Drive Bay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hw_component_status{job=\"$job\", instance=\"$instance\", component_status=\"ok\", component_type=\"drive_bay\"} != 1",
     "legendFormat": "{{slot}}"
    }
   ]
  },
  {
   "title": "Failed nvram bay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hw_component_status{job=\"$job\", instance=\"$instance\", component_status=\"ok\", component_type=\"nvram_bay\"} != 1",
     "legendFormat": "{{slot}}"
    }
   ]
  },
  {
   "title": "Failed power supply",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hw_component_status{job=\"$job\", instance=\"$instance\", component_status=\"ok\", component_type=\"power_supply\"} != 1",
     "legendFormat": "{{slot}}"
    }
   ]
  },
  {
   "title": "Failed fc port",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hw_component_status{job=\"$job\", instance=\"$instance\", component_status=\"ok\", component_type=\"fc_port\"} != 1",
     "legendFormat": "{{slot}}"
    }
   ]
  },
  {
   "title": "Failed ethernet port",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hw_component_status{job=\"$job\", instance=\"$instance\", component_status=\"ok\", component_type=\"eth_port\"} != 1",
     "legendFormat": "{{slot}}"
    }
   ]
  },
  {
   "title": "Failed cooling sensor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hw_component_status{job=\"$job\", instance=\"$instance\", component_status=\"ok\", component_type=\"cooling\"} != 1",
     "legendFormat": "{{slot}}"
    }
   ]
  },
  {
   "title": "Failed sas port",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hw_component_status{job=\"$job\", instance=\"$instance\", component_status=\"ok\", component_type=\"sas_port\"} != 1",
     "legendFormat": "{{slot}}"
    }
   ]
  },
  {
   "title": "Failed temp sensor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hw_component_status{job=\"$job\", instance=\"$instance\", component_status=\"ok\", component_type=\"temp_sensor\"}  != 1",
     "legendFormat": "{{slot}}"
    }
   ]
  }
 ]
}